### ISSUE TITLE
Opening the inventory crashes my game

### ISSUE THREAD

**Issue by Tanjiraaaaa** [A5ho9999/MinecraftMods#17]
### Mod name

Brrrrock (Yeeterite)

### Mod Version

3.0.0

### Minecraft Version

1.20.6

### Fabric Versions

0.15.11

### Confirmation Checkboxes

- [X] I have confirmed that this issue can be reproduced with minimal setup (Not a large Modpack)
- [X] I am NOT using a 3rd Party Client (Feather Client, Luna Client, etc)

### Issue Description

I haven't really confirmed that it works without a large modpack. But I have confirmed that my game does not crash when I had removed the mod from the modpack.
Everytime I open my inventory upon joining a new world, my game crashes entirely.

### Steps to reproduce

1. Go into a world (singleplayer for me)
2. Open your inventory
3. Minecraft crashes

### Expected Behavior

My inventory should've opened normally.

### Crash Report / Log

https://mclo.gs/hezzWt9

**Comment by A5ho9999** [comment]
This appears to be an issue with owo-lib conflicting with another mod, most likely one that is editing the inventory screens. You can try to update to v[0.12.9](https://modrinth.com/mod/owo-lib/version/0.12.9+1.20.5) to see if that resolves it, otherwise you will need to make a report over at their [GitHub](https://github.com/wisp-forest/owo-lib/issues?q=is%3Aopen+is%3Aissue)

You are also using a 3rd Party Client which more than likely the actual issue.

**Comment by Tanjiraaaaa** [comment]
Huh that's strange, I don't think I'm using a third party client since it's the launcher from the Microsoft Store itself

**Comment by A5ho9999** [comment]
Your log displays Meteor Client which counts as a 3rd party client
